# code: language=Ansible insertSpaces=true tabSize=2


# Kubernetes
#
# Install and start Kubernetes on every hosts.

- include_tasks:
    file: "install_{{ ansible_distribution|lower }}.yml"


- name: Install Kubernetes
  package:
    name: "{{ jpclipffel_k8s_k8s_packages }}"
    state: present


- name: Start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes


# Python
#
# Install PIP and Ansible dependencies to interact with Kubernetes on master nodes.
- block:
    # ---
    - name: Install Python PIP
      package:
        name:
          - python3-pip
        state: present
    # ---
    - name: Install Kubernetes Python dependencies for Ansible
      pip:
        name:
          - PyYAML
          - openshift
          - grpcio
          - docker
        state: present
  when:
    - jpclipffel_k8s_k8s_node_type == "master"
