# code: language=Ansible insertSpaces=true tabSize=2


- name: Stop and disable kubelet # noqa ignore-errors
  ansible.builtin.service:
    name: kubelet
    state: stopped
    enabled: no
  ignore_errors: yes


- name: Stop remaining services # noqa ignore-errors
  ansible.builtin.shell: >
    pkill -f {{ __srs_item }}
  loop:
    - kube-controller-manager
    - kube-proxy
    - kube-scheduler
    - kubelet
    - etcd
  loop_control:
    loop_var: __srs_item
  changed_when: true
  ignore_errors: yes


- name: Revert Kubernetes configuration # noqa ignore-errors
  ansible.builtin.shell: >
    kubeadm reset -f
  changed_when: true
  ignore_errors: yes


- name: Remove kubeconfig # noqa ignore-errors
  file:
    path: "{{ jpclipffel_k8s_k8s_kubeconfig }}"
    state: absent
  ignore_errors: yes


- name: Purge IPTables rules # noqa ignore-errors
  ansible.builtin.shell: |
    iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  changed_when: true
  ignore_errors: yes


- name: Cleanup tampered hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^.*{{ jpclipffel_k8s_k8s_control_plane_endpoint }}'
    state: absent
  when:
    - jpclipffel_k8s_k8s_control_plane_endpoint is defined and jpclipffel_k8s_k8s_control_plane_endpoint | length > 0
