# vim: set ft=Ansible ts=2


- name: Primary master node assertion
  ansible.builtin.assert:
    that:
      - jpclipffel_k8s_k8x_primary_master_node | default('') | length > 0
    fail_msg: "No primary master node selected (jpclipffel_k8s_k8x_primary_master_node)"
    quiet: true
  tags: [never, apply, delete]


- name: Create Tigera temporary directory
  ansible.builtin.tempfile:
    state: directory
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  register: "__tigera_files"
  tags: [never, apply, delete]


- name: Copy Tigera operator
  ansible.builtin.copy:
    src: "{{ jpclipffel_k8s_tigera_operator_manifest }}"
    dest: "{{ __tigera_files.path }}/{{ jpclipffel_k8s_tigera_operator_manifest | basename }}"
    mode: 0644
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  tags: [never, apply, delete]


- name: Templates CNI resources
  ansible.builtin.template:
    src: "{{ jpclipffel_k8s_tigera_resources_manifest }}"
    dest: "{{ __tigera_files.path }}/{{ jpclipffel_k8s_tigera_resources_manifest | basename }}"
    mode: 0644
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  tags: [never, apply, delete]


# ---


- name: Install Tigera operator
  kubernetes.core.k8s:
    src: "{{ __tigera_files.path }}/{{ jpclipffel_k8s_tigera_operator_manifest | basename }}"
    state: present
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  tags: [never, apply]


- name: Install CNI resources
  kubernetes.core.k8s:
    src: "{{ __tigera_files.path }}/{{ jpclipffel_k8s_tigera_resources_manifest | basename }}"
    state: present
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  tags: [never, apply]


# ---


- name: Uninstall CNI resources
  kubernetes.core.k8s:
    src: "{{ __tigera_files.path }}/{{ jpclipffel_k8s_tigera_resources_manifest | basename }}"
    state: absent
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  tags: [never, delete]


- name: Uninstall Tigera operator
  kubernetes.core.k8s:
    src: "{{ __tigera_files.path }}/{{ jpclipffel_k8s_tigera_operator_manifest | basename }}"
    state: absent
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  tags: [never, delete]


# ---


- name: Cleanup
  ansible.builtin.file:
    path: "{{ __tigera_files.path }}"
    state: absent
  when:
    - inventory_hostname == jpclipffel_k8s_k8x_primary_master_node
  tags: [never, apply, delete]
