# vim: set ft=Ansible ts=2


- name: Install Snapd
  ansible.builtin.package:
    name: "snapd"
    state: present
  tags: [never, setup]


- name: Configure Snapd
  ansible.builtin.systemd:
    name: "snapd.socket"
    enabled: true
    state: restared
  when:
    - ansible_system | lower == "linux"
    - ansible_distribution | lower not in ["ubuntu"]
  tags: [never, setup]

# ---

- name: Get microk8s status # noqa risky-shell-pipe
  ansible.builtin.shell: >
    snap list 2&>/dev/null
    | grep microk8s
    | awk '{print $4}'
  register: _gms
  changed_when: no
  tags: [never, setup]


- name: Control MicroK8s version
  ansible.builtin.fail:
    msg: "Requested MicroK8s version ({{ jpclipffel_k8s_microk8s_channel }}) does not match installed version ({{ _gms.stdout }})"
  when:
    - _gms.stdout | length > 0
    - jpclipffel_k8s_microk8s_channel != _gms.stdout
  tags: [never, setup]


- name: Install MicroK8s
  community.general.snap:
    name: "microk8s"
    channel: "{{ jpclipffel_k8s_microk8s_channel }}"
    classic: yes
    state: present
  tags: [never, setup]

- name: Setup MicroK8s DNS names
  ansible.builtin.lineinfile:
    path: "{{ jpclipffel_k8s_microk8s_dnsnames_path }}"
    line: "{{ __smdn.entry }} = {{ __smdn.host }}"
    insertafter: "^#MOREIPS$"
  with_items: "{{ jpclipffel_k8s_microk8s_dnsnames }}"
  loop_control:
    loop_var: __smdn
  changed_when: true
  tags: [never, setup]

# ---

- name: Enabling MicroK8s addons
  ansible.builtin.shell: |
    microk8s enable {{ __dmk8sa_item }}
  loop: "{{ jpclipffel_k8s_microk8s_addons }}"
  loop_control:
    loop_var: __dmk8sa_item
  changed_when: true
  tags: [never, apply]

# ---

- name: Disable MicroK8s addons
  ansible.builtin.shell: |
    microk8s disable {{ __dmk8sa_item }}
  loop: "{{ jpclipffel_k8s_microk8s_addons }}"
  loop_control:
    loop_var: __dmk8sa_item
  changed_when: true
  tags: [never, delete]

# ---

- name: Uninstall MicroK8s
  community.general.snap:
    name: "microk8s"
    state: absent
  tags: [never, teardown, remove]
